"""empty message

Revision ID: c70013cef827
Revises: f9bb05ee1f74
Create Date: 2021-08-26 16:05:46.033523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70013cef827'
down_revision = 'f9bb05ee1f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CitiesWeather', sa.Column('temperature', sa.Integer(), nullable=True))
    op.drop_column('CitiesWeather', 'temp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CitiesWeather', sa.Column('temp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('CitiesWeather', 'temperature')
    # ### end Alembic commands ###
