"""empty message

Revision ID: f9bb05ee1f74
Revises: 
Create Date: 2021-08-26 13:30:32.760138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9bb05ee1f74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CitiesWeather',
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('weather', sa.String(), nullable=True),
    sa.Column('temp', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('city')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CitiesWeather')
    # ### end Alembic commands ###
